4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2X2
empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array)

# 2. Initialize an all one array with size 4X2
ones_array = np.ones((4, 2))
print("\nAll Ones Array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with fill value
fill_value_array = np.full((3, 3), 7)
print("\nArray Filled with 7 (3x3):\n", fill_value_array)

# 4. Return a new array of zeros with same shape and type as a given array
reference_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(reference_array)
print("\nZeros Array with Same Shape as Reference Array:\n", zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(reference_array)
print("\nOnes Array with Same Shape as Reference Array:\n", ones_like_array)

# 6. Convert a list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted Numpy Array from List:\n", numpy_array)

Empty Array (2x2):
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array Filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Array with Same Shape as Reference Array:
 [[0 0 0]
 [0 0 0]]

Ones Array with Same Shape as Reference Array:
 [[1 1 1]
 [1 1 1]]

Converted Numpy Array from List:
 [1 2 3 4]


4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array1 = np.arange(20, 50)
print("1. Array from 10 to 49:")
print(array1)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
array2 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 Matrix with values from 0 to 8:")
print(array2)

# 3. Create a 3x3 identity matrix
array3 = np.eye(3)
print("\n3. 3x3 Identity Matrix:")
print(array3)

# 4. Create a random array of size 30 and find the mean
array4 = np.random.random(30)
mean4 = array4.mean()
print("\n4. Random array of size 30 and its mean:")
print(array4)
print("Mean:", mean4)

# 5. Create a 10x10 array with random values and find min and max
array5 = np.random.random((10, 10))
min5, max5 = array5.min(), array5.max()
print("\n5. 10x10 Array with random values:")
print(array5)
print("Minimum:", min5)
print("Maximum:", max5)

# 6. Create a zero array of size 10 and replace the 5th element with 1
array6 = np.zeros(10)
array6[4] = 1
print("\n6. Zero array with the 5th element replaced by 1:")
print(array6)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = arr[::-1]
print("\n7. Reversed array:")
print(reversed_arr)

# 8. Create a 2D array with 1 on the border and 0 inside
array8 = np.ones((5, 5))
array8[1:-1, 1:-1] = 0
print("\n8. 2D array with 1 on border and 0 inside:")
print(array8)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
array9 = np.zeros((8, 8), dtype=int)
array9[1::2, ::2] = 1
array9[::2, 1::2] = 1
print("\n9. 8x8 Matrix with a checkerboard pattern:")
print(array9)

1. Array from 10 to 49:
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]

2. 3x3 Matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30 and its mean:
[0.23735927 0.6443189  0.31556026 0.83894174 0.57117537 0.98875167
 0.92447963 0.0926369  0.96199594 0.35195791 0.67008481 0.85505557
 0.2250681  0.98847894 0.70707601 0.13496702 0.34480396 0.10115367
 0.12574541 0.6186719  0.76878587 0.80835469 0.15411451 0.49913832
 0.88272393 0.30780774 0.42900218 0.14598627 0.91432688 0.65420256]
Mean: 0.5420908646405329

5. 10x10 Array with random values:
[[0.32861672 0.15225736 0.13587475 0.46429012 0.8693416  0.52264184
  0.06499773 0.63035869 0.38980365 0.09245935]
 [0.86808279 0.23205193 0.75779937 0.66906639 0.49352506 0.25305951
  0.11734391 0.46243836 0.90346049 0.49052097]
 [0.72685042 0.6324247  0.48326544 0.18035766 0.8742619  0.23172765
  0.35247804 0.3

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("1. Addition of x and y:")
print(add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\n2. Subtraction of x and y:")
print(sub_xy)

# 3. Multiply the array with an integer (e.g., 2)
mul_x = x * 2
print("\n3. Multiplication of x with 2:")
print(mul_x)

# 4. Find the square of each element of the array
square_x = x ** 2
print("\n4. Square of each element in x:")
print(square_x)

# 5. Dot products
dot_vw = np.dot(v, w)  # Dot product of v and w
dot_xv = np.dot(x, v)  # Dot product of x and v
dot_xy = np.dot(x, y)  # Dot product of x and y
print("\n5. Dot products:")
print("v • w =", dot_vw)
print("x • v =")
print(dot_xv)
print("x • y =")
print(dot_xy)

# 6. Concatenate x and y along rows
concat_xy_rows = np.concatenate((x, y), axis=0)
print("\n6. Concatenation of x and y along rows:")
print(concat_xy_rows)

# Concatenate v and w along columns
concat_vw_cols = np.vstack((v, w))
print("\nConcatenation of v and w along columns:")
print(concat_vw_cols)

# 7. Attempt to concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\n7. Concatenation of x and v along rows:")
    print(concat_xv)
except ValueError as e:
    print("\n7. Error when concatenating x and v:")
    print(e)

# Explanation for the error
print("\nExplanation: The dimensions of x (2x2) and v (1D array of length 2) are incompatible for concatenation. To fix this, v must be reshaped to match the dimensions of x.")


1. Addition of x and y:
[[ 6  8]
 [10 13]]

2. Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

3. Multiplication of x with 2:
[[ 2  4]
 [ 6 10]]

4. Square of each element in x:
[[ 1  4]
 [ 9 25]]

5. Dot products:
v • w = 219
x • v =
[29 77]
x • y =
[[19 22]
 [50 58]]

6. Concatenation of x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
[[ 9 10]
 [11 12]]

7. Error when concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Explanation: The dimensions of x (2x2) and v (1D array of length 2) are incompatible for concatenation. To fix this, v must be reshaped to match the dimensions of x.


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
I = np.eye(2)
print("A * A^-1 (should be identity matrix):")
print(np.dot(A, A_inv))
print("\nIdentity matrix I:")
print(I)

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:")
print(AB)
print("\nBA:")
print(BA)
print("\nAB == BA?", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
B_T = np.transpose(B)
A_T = np.transpose(A)
print("\n(AB)^T:")
print(AB_T)
print("\nB^T * A^T:")
print(np.dot(B_T, A_T))
print("\n(AB)^T == B^T * A^T?", np.array_equal(AB_T, np.dot(B_T, A_T)))

#4
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("Solution [x, y, z]:")
print(X)

A * A^-1 (should be identity matrix):
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Identity matrix I:
[[1. 0.]
 [0. 1.]]

AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

AB == BA? False

(AB)^T:
[[23 51]
 [13 29]]

B^T * A^T:
[[23 51]
 [13 29]]

(AB)^T == B^T * A^T? True
Solution [x, y, z]:
[ 2.  1. -2.]
